var a=+prompt("enter value of a");
        var b=+prompt("enter value of b");
        console.log("inputs",a,b);
        console.log("add",a+b);
        console.log("sub",a-b);
        console.log("divide",a/b);
        console.log("multi",a*b);
        console.log("modulas",a%b);
        console.log("pre incre",++a);
        console.log("post incre",a++);
        console.log("pre decre",--a);
        console.log("post decre",a--);
        console.log("assign add",a+=5);
        console.log("assign sub",a-=5);
        console.log("assign multi",a*=5);
        console.log("assign percentage",a%=5);
        console.log("assign modulas",a/=5);
        console.log("a>b",a>b);
        console.log("a<b",a<b);
        console.log("a>=b",a>=b);
        console.log("a<=b",a<=b);
        console.log("a==b",a==b);
        console.log("a===b",a===b);
        console.log("a!=b",a!=b);
        console.log("true&&true",a>5 && b>5);
        console.log("true&&false",a>5 && b>100);
        console.log("false&&true",b>100 && a>5);
        console.log("false&&false",b>100 && b>100);
        console.log("true||true",a>5||b>5);
        console.log("true||false",a>5||b>100);
        console.log("false||true",b>100||a>5);
        console.log("false||false",b>100||b>100);